<?php

/* MorenwareDutilsBundle:Default:feeds.html.twig */
class __TwigTemplate_7d1396e10f544d16cd4ef6bb16a9d968666513ca4d24d4dbdb309512b6f7ca22 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = $this->env->loadTemplate("MorenwareDutilsBundle::base.html.twig");

        $this->blocks = array(
            'body' => array($this, 'block_body'),
        );
    }

    protected function doGetParent(array $context)
    {
        return "MorenwareDutilsBundle::base.html.twig";
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $this->parent->display($context, array_merge($this->blocks, $blocks));
    }

    // line 3
    public function block_body($context, array $blocks = array())
    {
        // line 4
        echo "<div ng-controller=\"feedsController\">
   <div class=\"row\">
\t    <div class=\"col-lg-12\">
\t     <h1 class=\"page-header\">Feeds</h1>
\t    </div>
\t</div>
\t<div class=\"row torrent-feeds\" ng-show=\"!loading\">
\t    <div class=\"col-lg-12\">
\t        <div class=\"panel panel-default\">
\t            <div class=\"panel-heading\">Feeds List
\t                <div class=\"pull-right\">
\t                    <div class=\"btn-group\">
\t                        <button type=\"button\" class=\"btn btn-primary\" ng-click=\"newFeed()\">
\t                            <span class=\"glyphicon glyphicon-plus\"></span>
\t                            New
\t                        </button>
\t                    </div>
\t                </div>
\t            </div>
\t                <div class=\"panel-body\">
\t                \t <!-- The 'item' passed in to editFeed() is a scoped value generated by the directive (see template) -->
\t                     <admin-table items=\"feeds\" fields=\"feedsFields\" update-action=\"editFeed(item)\"></admin-table>
\t                </div>
\t            </div>
\t    </div>
\t</div>


\t<div class=\"row\" ng-show=\"showFeedsForm\">
\t\t<!-- TODO: The form title and submit text are strings, so they can be passed as '@' in the directive, evaluating them here as [[formTitle]] / [[submitText]] -->
\t    <admin-form title=\"formTitle\" submit-text=\"submitText\" submit-action=\"action()\" fields=\"feedsFields\"></admin-form>
\t</div>

</div>
";
    }

    public function getTemplateName()
    {
        return "MorenwareDutilsBundle:Default:feeds.html.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  31 => 4,  28 => 3,);
    }
}
