<?php

namespace Morenware\DutilsBundle\Entity;

class TorrentState {

	const DOWNLOADING = "DOWNLOADING";
	const DOWNLOAD_COMPLETED = "DOWNLOAD_COMPLETED";
	const AWAITING_DOWNLOAD = "AWAITING_DOWNLOAD";
	const RENAMING = "RENAMING";
	const RENAMING_COMPLETED = "RENAMING_COMPLETED";
	const FETCHING_SUBTITLES = "FETCHING_SUBTITLES";
	const COMPLETED = "COMPLETED";
	const FAILED_DOWNLOAD_ATTEMPT = "FAILED_DOWNLOAD_ATTEMPT";
}