parameters:
#    morenware_dutils.example.class: Morenware\DutilsBundle\Example

services:
#    morenware_dutils.example:
#        class: %morenware_dutils.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
