require '../lib/angular.min.js'
require '../lib/angular-route.min.js'
require '../lib/angular-resource.min.js'
require './setup.coffee'
require './apiFactory.coffee'
require './instanceController.coffee'