_welcome:
    path:     /
    defaults: { _controller: "MorenwareDutilsBundle:Default:index" }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
    
_dutils:
    resource: "@MorenwareDutilsBundle/Controller"
    type:     annotation
