window._str = require '../lib/underscore.string.min.js'
window._ = require '../lib/underscore.min.js'
window.moment = require 'moment'

require '../lib/angular.min.js'
require '../lib/angular-route.min.js'
require '../lib/angular-resource.min.js'
require './setup.coffee'
require './searchFactory.coffee'
require './utilsService.coffee'
require './instanceController.coffee'
require './feeds.coffee'
require './feedsController.coffee'
require './components/adminForm.coffee'
require './components/adminTable.coffee'
require './searchController.coffee'
require './torrents.coffee'