morenware_dutils:
    resource: "@MorenwareDutilsBundle/Resources/config/routing.yml"
    prefix:   /base
    
morenware_dutils_rest:
    type: rest
    resource: "@MorenwareDutilsBundle/Resources/config/routing-rest.yml"
    prefix:   /api
    
logout:
  path: /logout


