security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER', 'ROLE_API' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN', 'ROLE_API' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        client:
            pattern:  ^/client
            security: false

        notify:
            pattern: ^/api/notify/.*$
            security: false

        secured_area:
            anonymous: ~
            provider: in_memory
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /
                always_use_default_target_path: true
            logout:
              path: /logout
              target: /login   
                
                
           