<?php

namespace Debril\RssAtomBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StreamController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Debril\RssAtomBundle\Controller\StreamController();
        return $instance;
    }
}
