<?php

namespace Morenware\DutilsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SearchTorrentsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Morenware\DutilsBundle\Controller\SearchTorrentsController();
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\SearchTorrentsController', 'serializer');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('jms_serializer', 1));
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\SearchTorrentsController', 'logger');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('logger', 1));
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\SearchTorrentsController', 'searchService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('search.service', 1));
        return $instance;
    }
}
