<?php

namespace Morenware\DutilsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class InstanceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Morenware\DutilsBundle\Controller\InstanceController();
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\InstanceController', 'instanceService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('instance.service', 1));
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\InstanceController', 'serializer');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('jms_serializer', 1));
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\InstanceController', 'torrentFeedService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('torrentfeed.service', 1));
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\InstanceController', 'logger');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('logger', 1));
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\InstanceController', 'asyncService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('async.service', 1));
        return $instance;
    }
}
