<?php

namespace Morenware\DutilsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class NotifyController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Morenware\DutilsBundle\Controller\NotifyController();
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\NotifyController', 'asyncService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('async.service', 1));
        $refProperty = new \ReflectionProperty('Morenware\\DutilsBundle\\Controller\\NotifyController', 'torrentFeedService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('torrentfeed.service', 1));
        return $instance;
    }
}
