morenware_dutils_base_homepage:
    path: /
    defaults: { _controller: "MorenwareDutilsBundle:Default:index" }
    
_dutils:
    resource: "@MorenwareDutilsBundle/Controller"
    type:     annotation
    